### ISSUE TITLE
Set a maxWidth to 90px to get a better rendering in french translation view

### ISSUE THREAD

**Issue by rbecheras** [sirap-group/tinymce-plugin-paragraph#13]
Here is the normal view (en_US):

![capture d ecran de 2016-09-15 23-05-59](https://cloud.githubusercontent.com/assets/6469390/18567870/69b69c5e-7b9a-11e6-8489-33e9af1907e2.png)

And the French translated view (fr_FR):

![capture d ecran de 2016-09-16 10-34-41](https://cloud.githubusercontent.com/assets/6469390/18580133/0808c04e-7bfa-11e6-9700-f9862c2f2f58.png)

As you can see, the `units` select box is not entirely shown.

But settting a maxWidth to the `Unit` label element should fix the issue, instead of having to increase the fieldset `maxWidth`

**Comment by rbecheras** [comment]
The translation should use abbreviations (for example) if it is to long for the native UI.
It must adapt to the plugin, not the opposite.
I close the issue.

**Comment by 1ucay** [comment]
its bad idea, bcs in Wordpress some string is native...only solution is replace native string in editor in Wordpres..How can I adapt lenght of strings in arabian language, vietnam etc..? :)) 

![image](https://cloud.githubusercontent.com/assets/15126471/20786361/ed80b8fc-b7a5-11e6-8427-860a91f91d27.png)

Also I have issue, if I choose 10CM margin for example -> then close paragraph box -> open paragraph box -> margin is 10 with PT unit, which is bad
